# Generated by Django 6.0.1 on 2026-01-08 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Mã khoa (vd: CNTT, KT, QT)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Tên khoa", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Mô tả về khoa", null=True),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Khoa còn hoạt động không"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Faculty",
                "verbose_name_plural": "Faculties",
                "db_table": "faculties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Mã ngành (vd: KTPM, HTTT)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Tên ngành", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Mô tả về ngành", null=True),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Ngành còn tuyển sinh không"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        help_text="Khoa chủ quản",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="majors",
                        to="academics.faculty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Major",
                "verbose_name_plural": "Majors",
                "db_table": "majors",
                "ordering": ["faculty", "name"],
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Mã lớp (vd: KTPM2021, HTTT2022A)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Tên lớp", max_length=200)),
                (
                    "academic_year",
                    models.PositiveIntegerField(
                        help_text="Năm học/khóa (vd: 2021, 2022)"
                    ),
                ),
                (
                    "max_students",
                    models.PositiveIntegerField(
                        default=50, help_text="Số sinh viên tối đa"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Mô tả về lớp", null=True),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Lớp còn hoạt động không"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "major",
                    models.ForeignKey(
                        help_text="Ngành học",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classes",
                        to="academics.major",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "db_table": "classes",
                "ordering": ["major", "-academic_year", "name"],
            },
        ),
    ]
